//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public string kayitId { get; set; }
        public string kayitEpinId { get; set; }
        public string kayitKullaniciId { get; set; }
    
        public virtual Epin Epin { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
